spring.application.name=webapptraining
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.thymeleaf.enabled=true
spring.web.resources.static-locations=classpath:/static/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
